/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: user.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "user.pb-c.h"
void   user__init
                     (User         *message)
{
  static User init_value = USER__INIT;
  *message = init_value;
}
size_t user__get_packed_size
                     (const User *message)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user__pack
                     (const User *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user__pack_to_buffer
                     (const User *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
User *
       user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (User *)
     protobuf_c_message_unpack (&user__descriptor,
                                allocator, len, data);
}
void   user__free_unpacked
                     (User *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor user__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "age",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(User, has_age),
    offsetof(User, age),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, phone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user__field_indices_by_name[] = {
  3,   /* field[3] = address */
  2,   /* field[2] = age */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  4,   /* field[4] = phone */
};
static const ProtobufCIntRange user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "User",
  "User",
  "User",
  "",
  sizeof(User),
  5,
  user__field_descriptors,
  user__field_indices_by_name,
  1,  user__number_ranges,
  (ProtobufCMessageInit) user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
