C str
      LOGICAL NAME(8)
      READ (*,100) NAME
      READ (*,110) MONEY,INCOME
      WRITE (*,120) NAME
      WRITE (*,130) MONEY
      IF (1000 * MONEY .GT. INCOME) GO TO 10
      WRITE(*,140)
      GO TO 20
 10   WRITE(*,150)
 20   CONTINUE
      WRITE(*,160)
      STOP
 100  FORMAT(8A1)
 110  FORMAT(2I5)
 120  FORMAT(' DEAR MR ',8A1)
 130  FORMAT(5X,'THANK YOU SO MUCH FOR YOUR LAST'
     +     'YEAR''S'/' CONTRIBUTION OF', I4,' DOLLARS.'/
     +     5X,'SINCE YOUR CONTRIBUTION LAST YEAR WAS')
 140  FORMAT(' NOT AS LARGE AS HOPED,WE NEED YOU')
 150  FORMAT(' SO GENEROUS, WE ARE COUTIONG NO YOU')
 160  FORMAT(' TO HELP US MEET OUR QUOTA THIS YEAR.'
     +     /20X,'YOURS SINCERELY.')
      END
